import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Search,ShoppingCart,User,Heart,MapPin,ChevronRight,Sparkles,Play,Plus,Minus,Trash2,MessageCircle,Package,ShieldCheck,Truck,Menu,X,SlidersHorizontal,LayoutDashboard,Box,Tag,BarChart3,CheckCircle,Clock,ChevronDown} from 'lucide-react';
import './styles.css';

const PAYMENTS={Airtel:'076 573 756',Moov:'060 156 160'};
const zones={Libreville:2500,Akanda:3000,Owendo:3000,'Autres zones':4000};
const cats=[
 ['Téléphones & accessoires','📱'],['Informatique','💻'],['Gaming','🎮'],['Mode','👕'],['Chaussures','👟'],['Beauté','💄'],['Cheveux','💇'],['Maison','🏠'],['Cuisine','🍳'],['Automobile','🚗'],['Solaire','☀️'],['Enfants','👶'],['Sport','🏋️'],['Bureau','🧾'],
 ['Cartes cadeaux','🎁'],['Gaming numérique','🎮'],['Streaming','🎬'],['IA & logiciels','🤖'],['Cloud','☁️'],['Ebooks & formations','📚'],['Templates','📄'],['Design','🎨'],['Réseaux sociaux','📱'],['Éducation','🎓'],['Services digitaux','💼'],['Productivité','📊']
];
const seeds={
 'Téléphones & accessoires':['Coque MagSafe Premium','Chargeur USB-C 25W','Écouteurs Bluetooth Pro','Câble USB-C tressé','Support téléphone voiture','Powerbank 20 000 mAh','Verre trempé HD','Adaptateur USB-C','Anneau support téléphone','Mini trépied smartphone'],
 'Informatique':['Souris sans fil silencieuse','Clavier Bluetooth','SSD externe 1 To','Hub USB-C 6-en-1','Webcam Full HD','Support ordinateur','Sacoche laptop 15 pouces','Clé USB 128 Go','Tapis de souris XXL','Casque USB'],
 'Gaming':['Manette sans fil PS5','Casque Gaming 7.1','Station de charge PS5','Câble HDMI 2.1','Support casque RGB','Tapis gaming XXL','Souris gaming','Clavier mécanique','Carte capture HDMI','Pochette console'],
 'Mode':['T-shirt Essential Gabon','Polo Premium','Chemise casual','Jean coupe droite','Sweat à capuche','Robe élégante','Pantalon cargo','Casquette brodée','Sac à main','Lunettes tendance'],
 'Chaussures':['Sneakers Urban','Baskets Running','Mocassins Classic','Sandales confort','Chaussures sport','Baskets montantes','Claquettes premium','Chaussures enfant','Chaussures bureau','Sneakers lifestyle'],
 'Beauté':['Parfum Eau de Parfum','Crème hydratante','Nettoyant visage','Sérum éclat','Rouge à lèvres','Mascara volume','Brosse visage','Coffret beauté','Lotion corps','Miroir LED'],
 'Cheveux':['Perruque naturelle','Extensions bouclées','Bonnet satin','Brosse démêlante','Gel coiffant','Huile capillaire','Shampoing doux','Après-shampoing','Peigne afro','Kit coiffure'],
 'Maison':['Lampe LED','Organiseur tiroir','Diffuseur parfum','Coussin déco','Horloge murale','Panier rangement','Rideau moderne','Miroir mural','Veilleuse','Multiprise'],
 'Cuisine':['Air fryer compact','Blender portable','Poêle antiadhésive','Set couteaux','Boîte alimentaire','Mug isotherme','Balance cuisine','Égouttoir','Mixeur plongeant','Gourde inox'],
 'Automobile':['Support téléphone voiture','Chargeur voiture USB-C','Compresseur portable','Tapis voiture','Caméra dashcam','Nettoyant intérieur','Organiseur coffre','Câbles démarrage','Pare-soleil','Lampe inspection'],
 'Solaire':['Lampe solaire extérieure','Kit solaire USB','Powerbank solaire','Projecteur solaire','Lampe torche rechargeable','Ampoule solaire','Ventilateur solaire','Guirlande solaire','Chargeur solaire','Mini panneau solaire'],
 'Enfants':['Sac à dos enfant','Jeu éducatif','Veilleuse enfant','Puzzle animaux','Gourde enfant','Trousse scolaire','Casque enfant','Livre coloriage','Boîte goûter','Jeu construction'],
 'Sport':['Corde à sauter','Tapis fitness','Bandes élastiques','Gourde sport','Sac de sport','Gants training','Rouleau massage','Ballon fitness','Chronomètre sport','Serviette microfibre'],
 'Bureau':['Carnet premium','Stylo gel','Support ordinateur','Agenda 2026','Lampe de bureau','Classeur A4','Post-it couleurs','Calculatrice','Organiseur bureau','Porte-documents'],
 'Cartes cadeaux':['Carte cadeau gaming 10€','Carte cadeau shopping 25€','Carte cadeau musique','Carte cadeau app store','Carte cadeau jeux PC','Carte cadeau console','Carte cadeau streaming','Carte cadeau e-commerce','Carte cadeau mobile','Carte cadeau numérique'],
 'Gaming numérique':['Code jeu PC officiel','Crédit console officiel','Abonnement gaming 1 mois','Extension jeu officielle','Pack monnaie virtuelle','Carte gaming numérique','Abonnement cloud gaming','DLC officiel','Bon d’achat gaming','Pass saison officiel'],
 'Streaming':['Abonnement streaming 1 mois','Bon streaming officiel','Abonnement musique 1 mois','Abonnement sport officiel','Carte vidéo numérique','Bon audio officiel','Abonnement famille officiel','Pass divertissement','Crédit plateforme','Bon cinéma numérique'],
 'IA & logiciels':['Licence logiciel bureautique','Outil IA productivité','Licence montage vidéo','Licence antivirus','Logiciel design officiel','Licence PDF','Outil transcription','Suite création','Licence gestion projet','Outil présentation'],
 'Cloud':['Stockage cloud 100 Go','Stockage cloud 1 To','Sauvegarde cloud','Pack cloud équipe','Bon cloud officiel','Stockage photo cloud','Licence cloud sécurité','Espace cloud pro','Backup ordinateur','Cloud collaboration'],
 'Ebooks & formations':['Ebook marketing digital','Formation Excel pratique','Ebook entrepreneuriat','Formation design','Guide réseaux sociaux','Formation productivité','Ebook finance personnelle','Cours bureautique','Formation e-commerce','Guide IA débutant'],
 'Templates':['Template CV professionnel','Template facture','Template budget','Template business plan','Template réseaux sociaux','Template présentation','Template calendrier contenu','Template devis','Template portfolio','Template planning'],
 'Design':['Pack icônes design','Kit identité visuelle','Templates Canva autorisés','Mockups produits','Pack polices sous licence','Kit présentation','Illustrations vectorielles','Pack logos éditables','Kit réseaux sociaux','Ressources design'],
 'Réseaux sociaux':['Pack templates Instagram','Calendrier éditorial','Kit stories','Guide croissance social media','Templates Reels','Pack légendes','Kit branding social','Planificateur contenu','Audit réseaux sociaux','Service création contenu'],
 'Éducation':['Cours anglais débutant','Pack exercices maths','Formation bureautique','Fiches révision','Cours programmation','Cours communication','Ebook apprentissage','Pack vocabulaire','Formation prise de parole','Ressources scolaires'],
 'Services digitaux':['Création CV','Création visuels social media','Montage vidéo court','Mise en page document','Création présentation','Conseil e-commerce','Configuration boutique','Optimisation profil','Service transcription','Assistance digitale'],
 'Productivité':['Template Notion','Planner numérique','Pack checklist','Gestionnaire budget','Template projet','Pack objectifs','Agenda numérique','Dashboard productivité','Kit organisation','Template suivi habitudes']
};
const basePrices={
 'Téléphones & accessoires':8500,'Informatique':12000,Gaming:18000,Mode:10000,Chaussures:15000,Beauté:7500,Cheveux:12000,Maison:6500,Cuisine:9000,Automobile:8500,Solaire:11000,Enfants:6000,Sport:7000,Bureau:3500,'Cartes cadeaux':7000,'Gaming numérique':9000,Streaming:6000,'IA & logiciels':12000,Cloud:8000,'Ebooks & formations':5000,Templates:4500,Design:7500,'Réseaux sociaux':6000,Éducation:5000,'Services digitaux':10000,Productivité:4500};
const iconFor=cats.reduce((a,[n,i])=>(a[n]=i,a),{});
function imgFor(cat,index){const hue=(index*47)%360; return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="hsl(${hue},55%,22%)"/><stop offset="1" stop-color="hsl(${(hue+55)%360},70%,46%)"/></linearGradient></defs><rect width="600" height="600" rx="48" fill="url(#g)"/><circle cx="300" cy="270" r="150" fill="rgba(255,255,255,.12)"/><text x="300" y="285" text-anchor="middle" font-size="110" font-family="Arial">${iconFor[cat]||'🛍️'}</text><text x="300" y="470" text-anchor="middle" font-size="28" fill="white" font-family="Arial" font-weight="700">GabonMarket</text><text x="300" y="510" text-anchor="middle" font-size="18" fill="rgba(255,255,255,.8)" font-family="Arial">${cat}</text></svg>`)} `}
function makeProducts(){let id=1,arr=[]; for(const [cat,items] of Object.entries(seeds)){items.forEach((name,j)=>{for(let k=0;k<Math.max(1,Math.ceil(500/(Object.keys(seeds).length*10)));k++){if(arr.length>=500)break; const price=basePrices[cat]+((j*1300+k*700)%7)*1000; const sale=(j+k)%5===0; arr.push({id:id++,name:k?`${name} ${k+1}`:name,category:cat,price:sale?Math.round(price*.85):price,oldPrice:sale?price:null,stock:5+((j+k)%20),image:imgFor(cat,id),description:`Une sélection ${cat.toLowerCase()} pensée pour les clients au Gabon. Produit de démonstration remplaçable par la photo fournisseur.`,digital:['Cartes cadeaux','Gaming numérique','Streaming','IA & logiciels','Cloud','Ebooks & formations','Templates','Design','Réseaux sociaux','Éducation','Services digitaux','Productivité'].includes(cat)});}}); if(arr.length>=500)break;} return arr.slice(0,500)}
const PRODUCTS=makeProducts();
const money=n=>new Intl.NumberFormat('fr-FR').format(n)+' FCFA';
function App(){
 const [view,setView]=useState('home'),[query,setQuery]=useState(''),[category,setCategory]=useState('Toutes'),[cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('gm-cart')||'[]')),[favorites,setFavorites]=useState([]),[selected,setSelected]=useState(null),[ai,setAi]=useState(''),[mobileNav,setMobileNav]=useState(false),[showCheckout,setShowCheckout]=useState(false),[admin,setAdmin]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>localStorage.setItem('gm-cart',JSON.stringify(cart)),[cart]);
 const results=useMemo(()=>PRODUCTS.filter(p=>(category==='Toutes'||p.category===category)&&(!query||`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()))),[query,category]);
 const aiResults=useMemo(()=>{const q=ai.toLowerCase(); let budget=Infinity; const m=q.match(/(\d[\d\s.]*)\s*(?:fcfa|f|franc)/i); if(m) budget=parseInt(m[1].replace(/\D/g,''))||Infinity; let pool=PRODUCTS.filter(p=>p.price<=budget); const terms=q.split(/\s+/).filter(x=>x.length>3); pool=pool.sort((a,b)=>score(b,terms,q)-score(a,terms,q)); return (pool.length?pool:PRODUCTS).slice(0,6)},[ai]);
 function score(p,terms,q){let s=0; const text=(p.name+' '+p.category+' '+p.description).toLowerCase(); terms.forEach(t=>{if(text.includes(t))s+=3}); if(q.includes('ps5')&&p.category==='Gaming')s+=8; if((q.includes('cadeau')||q.includes('copine'))&&(p.category==='Beauté'||p.category==='Mode'||p.category==='Cheveux'))s+=7; if(q.includes('téléphone')&&p.category==='Téléphones & accessoires')s+=8; return s}
 const add=(p)=>{setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...c,{...p,qty:1}]}); notify('Ajouté au panier');};
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const remove=id=>setCart(c=>c.filter(x=>x.id!==id)); const change=(id,d)=>setCart(c=>c.map(x=>x.id===id?{...x,qty:Math.max(1,x.qty+d)}:x));
 const subtotal=cart.reduce((s,x)=>s+x.price*x.qty,0);
 return <div className="app">
  <header className="header"><div className="top"><button className="icon mobile" onClick={()=>setMobileNav(!mobileNav)}>{mobileNav?<X/>:<Menu/>}</button><button className="brand" onClick={()=>{setView('home');setCategory('Toutes')}}><span className="logoMark">G</span><span>Gabon<span>Market</span></span></button><div className="search"><Search/><input value={query} onChange={e=>{setQuery(e.target.value);setView('shop')}} placeholder="Rechercher un produit…"/><button onClick={()=>setView('shop')}>Rechercher</button></div><button className="icon" onClick={()=>setView('account')}><User/><small>Compte</small></button><button className="cartBtn" onClick={()=>setView('cart')}><ShoppingCart/><b>{cart.reduce((s,x)=>s+x.qty,0)}</b><small>Panier</small></button></div>
  <nav className={mobileNav?'nav open':'nav'}>{cats.map(([n,i])=><button key={n} onClick={()=>{setCategory(n);setView('shop');setMobileNav(false)}}>{i} {n}</button>)}<button className="adminLink" onClick={()=>setAdmin(true)}><LayoutDashboard/> Admin</button></nav></header>
  {view==='home'&&<Home ai={ai} setAi={setAi} aiResults={aiResults} add={add} setSelected={setSelected} setView={setView} setCategory={setCategory}/>} 
  {view==='shop'&&<Shop results={results} category={category} setCategory={setCategory} add={add} setSelected={setSelected} favorites={favorites} setFavorites={setFavorites}/>} 
  {view==='cart'&&<Cart cart={cart} change={change} remove={remove} subtotal={subtotal} checkout={()=>setShowCheckout(true)}/>} 
  {view==='account'&&<Account/>}
  {selected&&<ProductModal p={selected} add={add} close={()=>setSelected(null)} />}
  {showCheckout&&<Checkout cart={cart} subtotal={subtotal} close={()=>setShowCheckout(false)} clear={()=>{setCart([]);setShowCheckout(false);setView('home');notify('Commande préparée') }}/>} 
  {admin&&<Admin close={()=>setAdmin(false)} products={PRODUCTS}/>} 
  {toast&&<div className="toast">✓ {toast}</div>}
  <footer><div><b>GabonMarket</b><p>La marketplace pensée pour le Gabon.</p></div><div><b>Paiements</b><p>Airtel Money · 076 573 756<br/>Moov Money · 060 156 160</p></div><div><b>Livraison</b><p>Libreville · Akanda · Owendo<br/>Zones configurables</p></div><div><b>Sécurité</b><p>Transactions et données protégées.</p></div></footer>
 </div>
}
function Home({ai,setAi,aiResults,add,setSelected,setView,setCategory}){return <main><section className="hero"><div><div className="pill">🇬🇦 Livraison au Gabon uniquement</div><h1>Tout ce qu’il vous faut.<br/><em>Au Gabon.</em></h1><p>Une marketplace rapide, moderne et pensée d’abord pour votre smartphone.</p><div className="heroBtns"><button className="primary" onClick={()=>setView('shop')}>Explorer la boutique <ChevronRight/></button><button className="ghost" onClick={()=>document.getElementById('ia').scrollIntoView({behavior:'smooth'})}><Sparkles/> Essayer GabonMarket IA</button></div></div><div className="heroCard"><div className="heroOrb">🇬🇦</div><b>+500 produits</b><span>physiques & numériques</span><div className="miniStats"><span>⚡ Rapide</span><span>📱 Mobile-first</span><span>🚚 Local</span></div></div></section>
 <section id="ia" className="aiBox"><div className="aiHead"><div className="aiIcon"><Sparkles/></div><div><h2>GabonMarket IA</h2><p>Décrivez ce que vous cherchez, je trouve les meilleures options.</p></div></div><div className="aiInput"><Sparkles/><input value={ai} onChange={e=>setAi(e.target.value)} placeholder="Ex. Un cadeau pour ma copine avec 20 000 FCFA…"/><button className="primary">Trouver</button></div>{ai&&<div className="aiResults">{aiResults.map(p=><ProductCard key={p.id} p={p} add={add} setSelected={setSelected}/>)}</div>}<div className="chips"><button onClick={()=>setAi('Je veux des accessoires PS5 avec moins de 30 000 FCFA')}>🎮 Accessoires PS5 &lt; 30 000</button><button onClick={()=>setAi('Cadeau pour ma copine avec 20 000 FCFA')}>🎁 Cadeau &lt; 20 000</button><button onClick={()=>setAi('Quelque chose d’utile pour mon téléphone à moins de 10 000 FCFA')}>📱 Téléphone &lt; 10 000</button></div></section>
 <section><SectionTitle title="Catégories"/><div className="catGrid">{cats.slice(0,14).map(([n,i])=><button key={n} onClick={()=>{setCategory(n);setView('shop')}}><span>{i}</span><b>{n}</b></button>)}</div></section>
 <section><SectionTitle title="🔥 Les plus populaires" action="Voir tout" onClick={()=>setView('shop')}/><div className="productGrid">{PRODUCTS.slice(0,8).map(p=><ProductCard key={p.id} p={p} add={add} setSelected={setSelected}/>)}</div></section>
 <section className="promo"><div><span>OFFRE GABONMARKET</span><h2>Des essentiels du quotidien<br/>à prix malin.</h2><p>Livraison locale et paiement mobile.</p><button className="primary" onClick={()=>setView('shop')}>Découvrir les offres</button></div><div className="promoIcon">🛍️</div></section>
 <section><SectionTitle title="💻 Le digital, en toute légalité"/><div className="productGrid">{PRODUCTS.filter(p=>p.digital).slice(0,8).map(p=><ProductCard key={p.id} p={p} add={add} setSelected={setSelected}/>)}</div></section>
 </main>}
function SectionTitle({title,action,onClick}){return <div className="sectionTitle"><h2>{title}</h2>{action&&<button onClick={onClick}>{action}<ChevronRight/></button>}</div>}
function ProductCard({p,add,setSelected}){const [pub,setPub]=useState(false);return <article className="card"><div className="pic" onClick={()=>setSelected(p)}><img src={p.image}/>{p.oldPrice&&<span className="sale">-{Math.round((1-p.price/p.oldPrice)*100)}%</span>}<button className="mini" onClick={e=>{e.stopPropagation();setPub(true)}}><Play size={14}/> Mini pub</button></div><div className="cardBody"><small>{p.category}</small><h3 onClick={()=>setSelected(p)}>{p.name}</h3><div className="price">{money(p.price)} {p.oldPrice&&<del>{money(p.oldPrice)}</del>}</div><div className="stock">● {p.stock>0?'En stock':'Rupture'}</div><button className="add" onClick={()=>add(p)}><Plus/> Ajouter au panier</button></div>{pub&&<MiniAd p={p} close={()=>setPub(false)} add={add}/>}</article>}
function MiniAd({p,close,add}){return <div className="adOverlay"><div className="ad"><button className="close" onClick={close}><X/></button><span>🔥 OFFRE GABONMARKET</span><img src={p.image}/><h3>{p.name}</h3><b>{money(p.price)}</b><p>« Une solution pratique, pensée pour votre quotidien au Gabon. »</p><button className="primary" onClick={()=>{add(p);close()}}>Acheter</button></div></div>}
function Shop({results,category,setCategory,add,setSelected,favorites,setFavorites}){return <main><div className="shopHead"><div><span className="eyebrow">GABONMARKET</span><h1>{category==='Toutes'?'Tous les produits':category}</h1><p>{results.length} produits disponibles</p></div><button className="filter"><SlidersHorizontal/> Filtres</button></div><div className="catStrip"><button className={category==='Toutes'?'active':''} onClick={()=>setCategory('Toutes')}>Tout</button>{cats.map(([n,i])=><button className={category===n?'active':''} key={n} onClick={()=>setCategory(n)}>{i} {n}</button>)}</div><div className="productGrid">{results.map(p=><div key={p.id} className="favWrap"><ProductCard p={p} add={add} setSelected={setSelected}/><button className="heart" onClick={()=>setFavorites(f=>f.includes(p.id)?f.filter(x=>x!==p.id):[...f,p.id])}><Heart fill={favorites.includes(p.id)?'currentColor':'none'}/></button></div>)}</div>{!results.length&&<div className="empty"><Search/><h2>Aucun produit trouvé</h2><p>Essayez un autre mot-clé.</p></div>}</main>}
function Cart({cart,change,remove,subtotal,checkout}){return <main className="cartPage"><div className="shopHead"><div><span className="eyebrow">VOTRE PANIER</span><h1>Panier</h1></div></div>{cart.length?<div className="cartLayout"><div>{cart.map(x=><div className="cartItem" key={x.id}><img src={x.image}/><div className="cartInfo"><small>{x.category}</small><h3>{x.name}</h3><b>{money(x.price)}</b></div><div className="qty"><button onClick={()=>change(x.id,-1)}><Minus/></button><span>{x.qty}</span><button onClick={()=>change(x.id,1)}><Plus/></button></div><button className="trash" onClick={()=>remove(x.id)}><Trash2/></button></div>)}</div><aside className="summary"><h2>Résumé</h2><div><span>Sous-total</span><b>{money(subtotal)}</b></div><div><span>Livraison</span><span>Calculée à l’adresse</span></div><hr/><div className="total"><span>Total estimé</span><b>{money(subtotal)}</b></div><button className="primary full" onClick={checkout}>Passer la commande <ChevronRight/></button><p className="secure"><ShieldCheck/> Paiement mobile local</p></aside></div>:<div className="empty"><ShoppingCart/><h2>Votre panier est vide</h2><p>Ajoutez vos produits préférés pour commencer.</p></div>}</main>}
function Checkout({cart,subtotal,close,clear}){const [op,setOp]=useState('Airtel'),[form,setForm]=useState({name:'',phone:'',city:'Libreville',zone:'Libreville',address:'',note:''});const delivery=zones[form.zone]||0,total=subtotal+delivery;const msg=`Bonjour GabonMarket, je souhaite confirmer ma commande.%0A%0A${cart.map(x=>`• ${x.name} x${x.qty} — ${money(x.price*x.qty)}`).join('%0A')}%0A%0ATotal: ${money(total)}%0APaiement: ${op} Money (${PAYMENTS[op]})%0ANom: ${form.name}%0ATéléphone: ${form.phone}%0AVille: ${form.city}%0AQuartier/zone: ${form.zone}%0AAdresse/repère: ${form.address}%0A${form.note?'Position/repère WhatsApp: '+form.note:''}`;return <div className="modalBg"><div className="checkout"><button className="close" onClick={close}><X/></button><div className="checkoutHead"><Package/><div><h2>Finaliser la commande</h2><p>Livraison au Gabon uniquement</p></div></div><div className="payTabs"><button className={op==='Airtel'?'active':''} onClick={()=>setOp('Airtel')}>🔴 Airtel Money</button><button className={op==='Moov'?'active':''} onClick={()=>setOp('Moov')}>🟢 Moov Money</button></div><p className="payNumber">Envoyez le paiement à <b>{PAYMENTS[op]}</b></p><div className="formGrid">{[['name','Nom complet'],['phone','Téléphone'],['city','Ville']].map(([k,l])=><label key={k}>{l}<input value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={l}/></label>)}<label>Zone de livraison<select value={form.zone} onChange={e=>setForm({...form,zone:e.target.value})}>{Object.entries(zones).map(([z,v])=><option key={z}>{z}</option>)}</select></label><label className="wide">Adresse / repère<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Quartier, rue, immeuble, repère…"/></label><label className="wide">Position WhatsApp (facultatif)<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Collez votre position ou ajoutez un repère"/></label></div><div className="checkoutTotal"><span>Produits <b>{money(subtotal)}</b></span><span>Livraison <b>{money(delivery)}</b></span><strong>Total <b>{money(total)}</b></strong></div><a className="whatsapp" href={`https://wa.me/241${op==='Airtel'?'76573756':'60156160'}?text=${msg}`} target="_blank" rel="noreferrer" onClick={clear}><MessageCircle/> Confirmer via WhatsApp</a><small className="legal">Les moyens de paiement automatisés pourront être branchés ultérieurement via les API officielles des opérateurs.</small></div></div>}
function ProductModal({p,add,close}){return <div className="modalBg"><div className="productModal"><button className="close" onClick={close}><X/></button><img src={p.image}/><div><small>{p.category}</small><h2>{p.name}</h2><p>{p.description}</p><div className="price big">{money(p.price)} {p.oldPrice&&<del>{money(p.oldPrice)}</del>}</div><div className="feature"><span>✓ Disponible</span><span>🚚 Livraison Gabon</span><span>{p.digital?'⚡ Livraison numérique':'📦 Produit physique'}</span></div><button className="primary full" onClick={()=>{add(p);close()}}>Ajouter au panier</button><button className="buyNow" onClick={()=>{add(p);close()}}>Acheter maintenant</button></div></div></div>}
function Account(){return <main><div className="account"><div className="accountIcon"><User/></div><h1>Votre espace client</h1><p>La connexion, les favoris, adresses et historique sont prêts à être branchés à un backend sécurisé.</p><div className="accountCards"><div><Heart/><b>Favoris</b><span>Retrouvez vos produits préférés</span></div><div><Package/><b>Commandes</b><span>Suivez vos commandes</span></div><div><MapPin/><b>Adresses</b><span>Enregistrez vos repères</span></div></div><button className="primary">Créer mon compte</button></div></main>}
function Admin({close,products}){const [tab,setTab]=useState('dashboard');const [status,setStatus]=useState('Nouvelle commande');return <div className="adminBg"><div className="admin"><aside><button className="adminBrand" onClick={close}><span className="logoMark">G</span> GabonMarket</button>{[['dashboard','Tableau de bord',BarChart3],['products','Produits',Box],['orders','Commandes',Package],['promos','Promotions',Tag]].map(([id,l,I])=><button className={tab===id?'sel':''} onClick={()=>setTab(id)} key={id}><I/> {l}</button>)}<button onClick={close}><X/> Fermer</button></aside><section><div className="adminTop"><div><span className="eyebrow">ADMINISTRATION</span><h1>{tab==='dashboard'?'Vue d’ensemble':tab==='products'?'Catalogue':tab==='orders'?'Commandes':'Promotions'}</h1></div><span className="adminBadge">● Démo locale</span></div>{tab==='dashboard'&&<><div className="metrics"><div><BarChart3/><span>Ventes</span><b>2 480 000 FCFA</b><small>+18% ce mois</small></div><div><Package/><span>Commandes</span><b>148</b><small>12 en attente</small></div><div><Box/><span>Produits</span><b>{products.length}</b><small>catalogue actif</small></div><div><Truck/><span>Livraisons</span><b>26</b><small>en cours</small></div></div><div className="adminTable"><h2>Commandes récentes</h2>{['GM-1048','GM-1047','GM-1046','GM-1045'].map((x,i)=><div key={x}><b>{x}</b><span>{['Client Gabon','Client Akanda','Client Owendo','Client Libreville'][i]}</span><span>{money([78500,42000,12500,103000][i])}</span><select value={i===0?status:'Paiement confirmé'} onChange={e=>setStatus(e.target.value)}><option>Nouvelle commande</option><option>Paiement en attente</option><option>Paiement confirmé</option><option>Préparation</option><option>En livraison</option><option>Livrée</option><option>Annulée</option></select></div>)}</div></>}{tab==='products'&&<div className="adminTable"><div className="tableHeader"><h2>Catalogue produits</h2><button className="primary"><Plus/> Ajouter</button></div>{products.slice(0,30).map(p=><div key={p.id}><img src={p.image}/><b>{p.name}</b><span>{p.category}</span><span>{money(p.price)}</span><button>Modifier</button></div>)}</div>}{tab==='orders'&&<div className="adminTable"><h2>Gestion des commandes</h2><div className="orderGuide"><CheckCircle/> Statuts configurés : Nouvelle commande → Paiement en attente → Paiement confirmé → Préparation → En livraison → Livrée / Annulée.</div></div>}{tab==='promos'&&<div className="adminTable"><h2>Promotions</h2><div className="promoAdmin"><Tag/><div><b>Créer une promotion</b><p>Prix barré, remise, durée et produits concernés.</p></div><button className="primary">Nouvelle promo</button></div></div>}</section></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
